-- MySQL Script generated by MySQL Workbench
-- 12/18/17 01:22:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema default_schema
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `hotel` ;

-- -----------------------------------------------------
-- Schema hotel
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hotel` DEFAULT CHARACTER SET utf8 ;
USE `hotel` ;

-- -----------------------------------------------------
-- Table `hotel`.`room`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`room` ;

CREATE TABLE IF NOT EXISTS `hotel`.`room` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `price` DOUBLE NOT NULL,
  `capacity` INT NOT NULL,
  `status` VARCHAR(25) NOT NULL,
  `section` VARCHAR(25) NOT NULL,
  `rating` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`guest`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`guest` ;

CREATE TABLE IF NOT EXISTS `hotel`.`guest` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(15) NOT NULL,
  `surname` VARCHAR(15) NOT NULL,
  `fk_room_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fk_room_id`),
  INDEX `fk_room_id_idx` (`fk_room_id` ASC),
  CONSTRAINT `fk_guests_rooms1`
    FOREIGN KEY (`fk_room_id`)
    REFERENCES `hotel`.`room` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`service` ;

CREATE TABLE IF NOT EXISTS `hotel`.`service` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `price` DOUBLE NOT NULL,
  `section` VARCHAR(25) NOT NULL,
  `start_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `fk_guest_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fk_guest_id`),
  INDEX `fk_services_guests1_idx` (`fk_guest_id` ASC),
  CONSTRAINT `fk_services_guests1`
    FOREIGN KEY (`fk_guest_id`)
    REFERENCES `hotel`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `hotel`.`registration`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hotel`.`registration` ;

CREATE TABLE IF NOT EXISTS `hotel`.`registration` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `start_date` DATE NOT NULL,
  `final_date` DATE NOT NULL,
  `fk_room_id` INT NOT NULL,
  `fk_guest_id` INT NOT NULL,
  PRIMARY KEY (`id`, `fk_room_id`, `fk_guest_id`),
  INDEX `fk_registrations_rooms1_idx` (`fk_room_id` ASC),
  INDEX `fk_registrations_guests1_idx` (`fk_guest_id` ASC),
  CONSTRAINT `fk_registrations_rooms`
    FOREIGN KEY (`fk_room_id`)
    REFERENCES `hotel`.`room` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_registrations_guests`
    FOREIGN KEY (`fk_guest_id`)
    REFERENCES `hotel`.`guest` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
