-- MySQL Script generated by MySQL Workbench
-- 02/07/18 22:32:10
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema authentication
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `authentication` ;

-- -----------------------------------------------------
-- Schema authentication
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `authentication` DEFAULT CHARACTER SET utf8 ;
USE `authentication` ;

-- -----------------------------------------------------
-- Table `authentication`.`user_detail`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authentication`.`user_detail` ;

CREATE TABLE IF NOT EXISTS `authentication`.`user_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(20) NOT NULL,
  `surname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `authentication`.`auth`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `authentication`.`auth` ;

CREATE TABLE IF NOT EXISTS `authentication`.`auth` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `auth` VARCHAR(20) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `detail_fk` INT NOT NULL,
  PRIMARY KEY (`id`, `detail_fk`),
  INDEX `fk_user.creds_user.detail_idx` (`detail_fk` ASC),
  CONSTRAINT `fk_user.creds_user.detail`
    FOREIGN KEY (`detail_fk`)
    REFERENCES `authentication`.`user_detail` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
